### ISSUE TITLE
Could you provide some examples on how to use the structs?

### ISSUE THREAD

**Issue by Lennster1** [comblock/gopixel#4]

**Comment by comblock** [comment]
Could you elaborate? The structs are just a way to store the data from the hypixel api.

**Comment by comblock** [comment]
You should not have to use the structs package that comes with the library, go will automatically infer the type and you can just access the data by using struct.(data you want to access)

**Comment by Lennster1** [comment]
so how would i access the specific price in thebazaar data? sorry I'm new

**Comment by comblock** [comment]
I think you should have a look at this page
https://gobyexample.com/structs

> so how would i access the specific price in thebazaar data? sorry I'm new
`bazaar, err := client.Bazaar()
if err != nil {
   fmt.Println(err)
}
fmt.Println(bazaar.Products.Cactus.SellPrice)`

**Comment by comblock** [comment]
Do note, the structs are not set in stone, and I'm currently looking to change the bazaar struct to not use type embedding for the next version, this WILL break code using it when trying to upgrade.

**Comment by Lennster1** [comment]
ok ill  try to do some more research, thanks man!
