### ISSUE TITLE
What you are doing now do dosent get the full pages of the auction house on skyblock

### ISSUE THREAD

**Issue by UltimateBoi** [comblock/gopixel#5]
So basically you need the totalPages json element from /skyblock/auctions and add that int into a loop that gets that page

**Comment by comblock** [comment]
Okay so I looked at the API documentation and I'm seeing now that there are multiple different pages you have to individually get, I'll get working on this.

**Comment by comblock** [comment]
So I realised that when calling the function it will take a very long time and also potentially rate limit your api key so I will add a SkyblockActiveAuctionsPage() function and add a warning for the SkyblockActiveAuctions() function.

**Comment by UltimateBoi** [comment]
Yes indeed and also could you implement the use of fast http and make more examples please. I've already used this package for 2 days now and really liking it. Could you do more stuff around skyblock?

**Comment by UltimateBoi** [comment]
> So I realised that when calling the function it will take a very long time and also potentially rate limit your api key so I will add a SkyblockActiveAuctionsPage() function and add a warning for the SkyblockActiveAuctions() function.

also if its only once every api update, you will only be requesting 45-50 times a minute.

**Comment by UltimateBoi** [comment]
> Okay so I looked at the API documentation and I'm seeing now that there are multiple different pages you have to individually get, I'll get working on this.

no need btw, just add ?page= and then get total pages and loop it through all of them. If you want, ill send what ive done.

**Comment by comblock** [comment]
> Yes indeed and also could you implement the use of fast http and make more examples please. I've already used this package for 2 days now and really liking it. Could you do more stuff around skyblock?

I'm sorry that I didn't see your comment earlier, what would you like me to implement?

**Comment by UltimateBoi** [comment]
int pages = auctionsData.TotalPages;

loop  with i > pages

or whatever loop is in golang, im a js person lol

**Comment by comblock** [comment]
> int pages = auctionsData.TotalPages;
> 
> loop with i > pages
> 
> or whatever loop is in golang, im a js person lol

I already implemented it?

**Comment by UltimateBoi** [comment]
![image](https://user-images.githubusercontent.com/63293118/147267116-af39c528-63ba-48d0-b436-f98375273798.png)
oh ok nvm then
